# k8s/backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  JWT_SECRET: yourVerySecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurely
  JWT_EXPIRATION: "86400000"
  APP_FRONTEND_URL: "http://<GANTI_DENGAN_INGRESS_IP_NANTI>" # <<< ATUR SEBAGAI PLACEHOLDER DULU