apiVersion: v1
kind: Service
metadata:
  name: backend-service # Pastikan nama ini cocok dengan yang di nginx.conf frontend
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP