# k8s/backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  JWT_SECRET: yourVerySecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurely # Ganti dengan kunci rahasia yang kuat!
  JWT_EXPIRATION: "86400000"
  APP_FRONTEND_URL: "http://<GANTI_DENGAN_INGRESS_IP_NANTI>" # <<< ATUR SETELAH MENDAPATKAN IP INGRESS

  # --- Tambahan untuk Database Connection ---
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db-service.svc.cluster.local:5432/auth_db"
  # SPRING_DATASOURCE_URL: "jdbc:postgresql://db-service.backend.svc.cluster.local:5432/auth_db" -> NAMESPACE backend
  SPRING_DATASOURCE_USERNAME: "postgres" # Sesuai dengan nilai decode dari postgres-credentials secret
  SPRING_DATASOURCE_PASSWORD: "password" # Sesuai dengan nilai decode dari postgres-credentials secret