apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_USER: auth_user
  POSTGRES_PASSWORD: password # GANTI dengan password aman Anda!
  POSTGRES_DB: auth_db