apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # postgres
  username: cG9zdGdyZXM==
  # password
  password: cGFzc3dvcmQ=
  # customer-registration
  database: Y3VzdG9tZXItcmVnaXN0cmF0aW9u