apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bostang/auth-app-java-vue-backend:latest
        ports:
        - containerPort: 8081
        env:
        - name: APP_FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: APP_FRONTEND_URL # Ambil URL frontend dari Secret
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db-service:5432/auth_db # Gunakan nama Service DB
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: SERVER_PORT
          value: "8081" # Port aplikasi Spring Boot di dalam kontainer
        envFrom:
        - secretRef:
            name: backend-secrets # Ambil JWT_SECRET, JWT_EXPIRATION, APP_FRONTEND_URL
        # Tidak perlu 'command: ["sh", "-c", "sleep 15 && java -jar app.jar"]' di K8s.
        # Healthcheck akan menangani dependensi.