apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  JWT_SECRET: yourVerySecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurely # GANTI dengan secret yang sama
  JWT_EXPIRATION: "86400000"
  APP_FRONTEND_URL: "http://192.168.49.2:30080" # IP dari minikube URL frontend (dari sudut pandang browser) # ketika frontend service : NodePort (diatur statis)
  # APP_FRONTEND_URL: "http://127.0.0.1" # ketika frontend service : ClusterIP
  # yag akan di-allow CORS di backend
  # Misalnya, jika frontend Anda diakses dari http://192.168.49.2
  # INI MEMASTIKAN BACKEND MENGIZINKAN CORS DARI FRONTEND